### ISSUE TITLE
Question about improving opnmf() function's CPU performance

### ISSUE THREAD

**Issue by YuYT98** [anbai106/SOPNMF#5]
Dear Author,

I have observed that the current running time for the opnmf() function, when applied to a small-sized (about 50 subjects) voxel-level dataset, is rather extensive. To maximize CPU utilization, I attempted to modify the `n_threads` value from its default setting:

1. Directly within the `opnmf()` function in the **opnmf_core.py** script.
2. By updating the default value from 4 to 1 on line 186 of the cli.py file.

Despite these modifications, there hasn't been any noticeable enhancement in CPU performance. The algorithm continues to operate across multiple cores. Could you guide me on either modifying this `n_threads()` or other potential optimizations for better performance?

Thank you

**Comment by anbai106** [comment]
Hi, 

The opNMF algorithm is a batch learning method, which requires reading all the brain MRI scans into the memory and then updating the matrix factorization iteratively. So yes, it is computationally intensive. 

From my personal experience, running opNMF on my Ubuntu machine (32GB memory + 8CPU) takes 48 hours to converge the model for all parameters by default. One thing you can do is to downsample the resolution of your MRI scans. 

The parameter "n_threads" is defined for multi-thread computing in Numpy, but I don't know how Numpy efficiently (or not) handles this situation - I also had similar problems in defining the optimal number for this parameter. So, try it on your machine and find the optimal number... 

Thanks
