### ISSUE TITLE
How can we optimize the number of components for NMF?

### ISSUE THREAD

**Issue by tongluobing** [anbai106/SOPNMF#6]
Dear Junhao,

In the given example, there are two parameters: num_component_min and num_component_max. However, I didn't find an option specifically for tuning between these values. Does SOPNMF offer a solution for determining the optimal number of components, similar to the Reconstruction Error and Reproducibility methods mentioned in the study by Sotiras, A., Resnick, S.M., and Davatzikos, C. (2015) titled 'Finding imaging patterns of structural covariance via non-negative matrix factorization' in Neuroimage, 108, pp.1-16?

Thank you,
Jian

**Comment by anbai106** [comment]
Hi, 

Sorry that I did not see this before.

SOPNMF did not optimize this hyperparameter during modeling. Instead, you should define this a prior. Then you can use some other metric to choose the optimal C. For example, you can run the model from C=2 to 10, and then perform split-sample analysis and calculate the reproducibility index to find the peaking points.

Thanks

**Comment by tongluobing** [comment]
Hi Junhao,

Thanks for your explanation.

Best
